In [1]:
import numpy as np

In [6]:
y = np.array([[4,4,1,2,1,4,3,3,3]])

In [19]:
y[0,np.argsort(-y)][:,:3]

array([[4, 4, 4]])

In [20]:
dists = np.array([[4,4,1,2,1,4,3,3,3],[2,4,1,2,1,5,3,3,3]])

In [28]:
for i in range(2):
    cy = dists[i, np.argsort(dists[i])][:3]
    print(cy)

[1 1 2]
[1 1 2]


In [29]:
cy

array([1, 1, 2])

In [35]:
y = np.array([0,1,2,3,4])

In [34]:
y[cy]

array([1, 1, 2])

In [36]:
type(cy)

numpy.ndarray

In [37]:
type(y)

numpy.ndarray

In [38]:
cy

array([1, 1, 2])

In [39]:
cy.shape

(3,)

In [40]:
cy

array([1, 1, 2])

In [42]:
cy[:2]

array([1, 1])

In [44]:
cy[:-2]

array([1])

In [63]:
cy = [[0],[1],[2],[3],[4]]

In [46]:
n = 5

In [58]:
for i in range(n):
    tmp = cy
    print(tmp.remove(cy[i]))

None


IndexError: list index out of range

In [71]:
[i for i in cy if [i] != cy[1]]

[0, 1, 2, 3, 4]

In [64]:
np.average(cy)

2.0

In [72]:
cy = [np.array([1,2]),np.array([3,4])]

In [73]:
cy.join()

AttributeError: 'list' object has no attribute 'join'

In [75]:
np.vstack(cy)

array([[1, 2],
       [3, 4]])