In [1]:
import numpy as np

In [6]:
y = np.array([[4,4,1,2,1,4,3,3,3]])

In [19]:
y[0,np.argsort(-y)][:,:3]

array([[4, 4, 4]])

In [20]:
dists = np.array([[4,4,1,2,1,4,3,3,3],[2,4,1,2,1,5,3,3,3]])

In [28]:
for i in range(2):
    cy = dists[i, np.argsort(dists[i])][:3]
    print(cy)

[1 1 2]
[1 1 2]


In [29]:
cy

array([1, 1, 2])

In [35]:
y = np.array([0,1,2,3,4])

In [34]:
y[cy]

array([1, 1, 2])

In [36]:
type(cy)

numpy.ndarray

In [37]:
type(y)

numpy.ndarray

In [38]:
cy

array([1, 1, 2])

In [39]:
cy.shape

(3,)

In [40]:
cy

array([1, 1, 2])

In [42]:
cy[:2]

array([1, 1])

In [44]:
cy[:-2]

array([1])

In [63]:
cy = [[0],[1],[2],[3],[4]]

In [46]:
n = 5

In [58]:
for i in range(n):
    tmp = cy
    print(tmp.remove(cy[i]))

None


IndexError: list index out of range

In [71]:
[i for i in cy if [i] != cy[1]]

[0, 1, 2, 3, 4]

In [64]:
np.average(cy)

2.0

In [72]:
cy = [np.array([1,2]),np.array([3,4])]

In [73]:
cy.join()

AttributeError: 'list' object has no attribute 'join'

In [75]:
np.vstack(cy)

array([[1, 2],
       [3, 4]])

In [76]:
if 1==1:
    print("H")

H


In [77]:
W = np.array([[1,2,3],[4,5,6]])

In [78]:
X = np.array([[1,2],[3,4],[5,6],[7,8]])

In [108]:
y = np.array([1,0,2,1])

In [82]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [94]:
score = X.dot(W)

In [100]:
score[range(4),y]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (3,) 

In [101]:
score.shape

(4, 3)

In [115]:
margin = score - score[range(4),y].reshape(-1,1) + 1

In [126]:
margin>0

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [False,  True,  True]])

In [127]:
margin[margin>0]

array([ 1,  4,  1,  8, 15,  1,  1, 16])

In [128]:
margin

array([[ -2,   1,   4],
       [  1,   8,  15],
       [-21, -10,   1],
       [-14,   1,  16]])

In [121]:
score

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [123]:
help(np.mean)

Help on function mean in module numpy.core.fromnumeric:

mean(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in 

In [129]:
np.maximum(0,1)

1

In [131]:
margin[margin>0]=1

In [140]:
np.sum(margin,axis=0)

array([-36,  -7,   4])

In [137]:
margin

array([[ -2,   1,   1],
       [  1,   1,   1],
       [-21, -10,   1],
       [-14,   1,   1]])