In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
X = np.array([[1,2,3,4],[2,3,4,5]])

In [5]:
W = np.array([[1,2],[2,3],[3,4],[5,6]])

In [8]:
scores = X.dot(W)

In [32]:
scores.argmax(axis=1)

array([0, 1])

In [28]:
scores=np.array([[1,0],[2,3]])

In [33]:
scores

array([[1, 0],
       [2, 3]])

In [34]:
np.log(8)/np.log(3)

1.892789260714372

In [37]:
np.log(1e-5+1)

9.999950000398841e-06

In [40]:
np.log(np.e)

1.0

In [39]:
np.e

2.718281828459045

In [54]:
learning_rates = [1e-7, 5e-5]
learning_rates_rand = np.random.uniform(low=learning_rates[0],high=learning_rates[1], size = 20)/500+learning_rates[0] 

In [55]:
learning_rates_rand

array([1.63127264e-07, 1.00405887e-07, 1.23826007e-07, 1.56836424e-07,
       1.52079425e-07, 1.20187871e-07, 1.97688117e-07, 1.35282972e-07,
       1.84337797e-07, 1.27863098e-07, 1.57451257e-07, 1.15952454e-07,
       1.76093401e-07, 1.65110170e-07, 1.95669387e-07, 1.25486162e-07,
       1.13958413e-07, 1.60722712e-07, 1.32810256e-07, 1.85889060e-07])

In [48]:
np.log(np.log(np.log(2e-5+1)+1)+1)

1.9999400019867958e-05

In [2]:
s = np.array([[1,2],[3,4]])

In [7]:
np.max(s, axis = 1)

array([2, 4])

In [9]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
1/s

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])