In [1]:
import torch
from torch.autograd import Variable
import torchvision
import torchvision.transforms as T
import random

import numpy as np
from scipy.ndimage.filters import gaussian_filter1d
import matplotlib.pyplot as plt
from cs231n.image_utils import SQUEEZENET_MEAN, SQUEEZENET_STD
from PIL import Image
torch.cuda.set_device(3)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

In [ ]:
np.max(a,axis=1)

In [ ]:
b = torch.from_numpy(a)

In [ ]:
torch.max(b,1)

In [ ]:
device = torch.device("cuda:3" if torch.cuda.is_available() else "cpu")

In [ ]:
b.to(device)

In [4]:
torch.tensor([1]).shape

torch.Size([1])

In [9]:
c = torch.ones((1,2,3))

In [8]:
s1, s2, s3 = c.shape

In [11]:
s3

3

In [14]:
c.permute(1, 0, 2).shape

torch.Size([2, 1, 3])

In [2]:
c = torch.ones((2, 3))

In [7]:
torch.matmul(c, c.permute(1, 0))

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [37]:
e = np.ones((2,3))

In [39]:
e.dot(e.transpose(1,0)).shape

(2, 2)

In [4]:
c.permute(1,0).shape

torch.Size([3, 2])

In [10]:
c[:].matmul(c[:].permute(1, 0))

RuntimeError: number of dims don't match in permute

In [21]:
c = torch.ones((2,3,4))

In [22]:
a = [4,4,4]

In [23]:
for i, idx in enumerate(a):
    print(i, idx)

0 4
1 4
2 4


In [24]:
c = torch.tensor([0, 1, 2, 3])

In [26]:
c[1:]

tensor([ 1,  2,  3])

In [28]:
c[1:] - c[:-1]

tensor([ 1,  1,  1])

In [29]:
c

tensor([ 0,  1,  2,  3])